### PR TITLE
Update pydantic dependency to >= 2

### PR DESCRIPTION
**Pull request by dvzrv**
# Check List

Resolves: #<issue number here>

- [ ] I added **tests** for the changed code.
- [ ] I updated the **documentation** for the changed code.
- [x] I ran the **full** `tox` test suite locally, so the CI pipelines should be green.
- [x] I added the change to the CHANGELOG.md file.

I tried adapting the code for pydantic >= 2. However, there are still weird warnings in the `docs-*` tox targets that I can not figure out, so those will likely fail.
```
WARNING: Failed guarded type import with ImportError("cannot import name 'AbstractSetIntStr' from 'pydantic._internal._utils' (/home/user/rstcheck-core/.tox/docs/lib/python3.11/site-packages/pydantic/_internal/_utils.py)")
```
AFAICT, the type in question is not directly used in this code base but might be dragged in by something else. I can't figure out from where and how to not have the tox targets fail on this. Some feedback would be greatly appreciated!

Closes #44

### CODE REVIEW

**Comment by dvzrv** [comment]
cc @polyzen

**Comment by Cielquan** [comment]
Will try to take a look on it soon.

**Comment by hojo0590** [comment]
In case you need more time to figure this out `pydantic` offers `v1` support even in versions greater 2.0.  
So for a 'quick compatibility fix' you could go for `from pydantic import v1 as pydantic` (see their [Readme](https://github.com/pydantic/pydantic#pydantic-v110-vs-v2)) and tackle this in the _near_ future.

**Comment by Cielquan** [comment]
I think we should give it a bit more time before dropping support for v1. Therefore the approach suggested by @hojo0590 would be better. I guess an Import-Try-Except for the pydantic stuff would be the best way to implement this.

I would push the drop of v1 support to the end of this year. This should be plenty of time.

**Comment by Cielquan** [comment]
I just resolved the changelog merge conflict real quick.

**Pull request closed without merging**
